USE [VeriTabaniProjesi]
GO

/****** Nesnesi: Database [VeriTabaniProjesi] Betik Tarihi: 13.08.2026 08:01:16 ******/
CREATE DATABASE [VeriTabaniProjesi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VeriTabaniProjesi', FILENAME = N'C:\Users\emre.yilmaz\VeriTabaniProjesi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VeriTabaniProjesi_log', FILENAME = N'C:\Users\emre.yilmaz\VeriTabaniProjesi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VeriTabaniProjesi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VeriTabaniProjesi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET ARITHABORT OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VeriTabaniProjesi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VeriTabaniProjesi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VeriTabaniProjesi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VeriTabaniProjesi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [VeriTabaniProjesi] SET  MULTI_USER 
GO

ALTER DATABASE [VeriTabaniProjesi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VeriTabaniProjesi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VeriTabaniProjesi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VeriTabaniProjesi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VeriTabaniProjesi] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [VeriTabaniProjesi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [VeriTabaniProjesi] SET QUERY_STORE = ON
GO

ALTER DATABASE [VeriTabaniProjesi] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [VeriTabaniProjesi] SET  READ_WRITE 
GO

